const produtos = [
  {
    id: 1,
    nomeProduto: "Arroz Integral",
    categoria: "Alimentos",
    quantidade: 50,
    precoUnitario: 12.5,
    fornecedor: "Fazenda Grão Nobre",
    dataValidade: "2025-12-31",
  },
  {
    id: 2,
    nomeProduto: "Leite Desnatado",
    categoria: "Laticínios",
    quantidade: 100,
    precoUnitario: 4.99,
    fornecedor: "Laticínios Vaca Feliz",
    dataValidade: "2024-10-15",
  },
  {
    id: 3,
    nomeProduto: "Sabão em Pó",
    categoria: "Limpeza",
    quantidade: 30,
    precoUnitario: 22.8,
    fornecedor: "Limpeza Max",
    dataValidade: "2026-06-20",
  },
  {
    id: 4,
    nomeProduto: "Creme Dental",
    categoria: "Higiene Pessoal",
    quantidade: 80,
    precoUnitario: 7.5,
    fornecedor: "Sorriso Limpo",
    dataValidade: "2025-05-10",
  },
  {
    id: 5,
    nomeProduto: "Café Tradicional",
    categoria: "Alimentos",
    quantidade: 65,
    precoUnitario: 15.9,
    fornecedor: "Café da Roça",
    dataValidade: "2025-09-01",
  },
  {
    id: 6,
    nomeProduto: "Chocolate em Barra",
    categoria: "Doces",
    quantidade: 120,
    precoUnitario: 5.99,
    fornecedor: "Doces do Paraíso",
    dataValidade: "2024-11-25",
  },
  {
    id: 7,
    nomeProduto: "Shampoo Hidratante",
    categoria: "Higiene Pessoal",
    quantidade: 45,
    precoUnitario: 28.0,
    fornecedor: "Beleza Natural",
    dataValidade: "2026-03-18",
  },
  {
    id: 8,
    nomeProduto: "Refrigerante Cola",
    categoria: "Bebidas",
    quantidade: 8,
    precoUnitario: 6.5,
    fornecedor: "Bebidas Refrescantes",
    dataValidade: "2024-12-05",
  },
  {
    id: 9,
    nomeProduto: "Pão de Forma",
    categoria: "Padaria",
    quantidade: 90,
    precoUnitario: 8.9,
    fornecedor: "Pães da Vovó",
    dataValidade: "2024-10-20",
  },
  {
    id: 10,
    nomeProduto: "Água Mineral",
    categoria: "Bebidas",
    quantidade: 150,
    precoUnitario: 2.2,
    fornecedor: "Fonte Pura",
    dataValidade: "2025-07-01",
  },
];

export default { produtos };
